extends Node

# Background music autoload. Plays looping chiptune tracks (generated by
# tools/gen_music.py) and persists across scene changes, so asking for the track
# that's already playing is a no-op (no restart). Volume rides the Master bus,
# so the title's volume slider controls it too.

const TRACKS: Dictionary = {
	"title":  "res://assets/music/title.wav",
	"map":    "res://assets/music/map.wav",
	"battle": "res://assets/music/battle.wav",
}

var _player: AudioStreamPlayer
var _current: String = ""

func _ready() -> void:
	_player = AudioStreamPlayer.new()
	_player.bus = "Master"
	_player.volume_db = -9.0   # sit under the SFX
	add_child(_player)

func play(track: String) -> void:
	if track == _current and _player.playing:
		return
	if not TRACKS.has(track):
		return
	var stream = load(TRACKS[track])
	if stream is AudioStreamWAV:
		# Loop the whole sample seamlessly.
		stream.loop_mode = AudioStreamWAV.LOOP_FORWARD
		stream.loop_begin = 0
		stream.loop_end = int(stream.data.size() / 2)   # mono 16-bit -> 2 bytes/frame
	_current = track
	_player.stream = stream
	_player.play()

func stop() -> void:
	_current = ""
	if _player != null:
		_player.stop()
